spring:
  application:
    name: insurancewechatofficalaccount-wechat
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_insurancewechatofficalaccount?&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    #password: root
    password: mysql_123_HDY&
server:
  port: 8001
  servlet:
    context-path: /insurancewechatofficalaccount/wechat

yuexing:
  wechat:
    appId: wx5d1a3805b802505b
    secret: a9f94234c2773ae54367e31c99631fcb
    encryptToken: remylee
  auth:
    endpoint: https://open.weixin.qq.com/
  api:
    endpoint: https://api.weixin.qq.com/
    cors:
      path: /wechat/**
      origins: '*'
      method: GET,POST,PATCH,DELETE
      maxAge: 3600